### ISSUE TITLE
yolov3 bug

### ISSUE THREAD

**Issue by guoxianda** [tteepe/GaitGraph#1]
when I  run prepare_detection.py, there is a bug。   the weights of yolov3.weights is wrong？

Traceback (most recent call last):
  File "prepare_detection.py", line 81, in <module>
    detection(**vars(args))
  File "prepare_detection.py", line 28, in detection
    weights_path="../../models/yolov3.weights",
  File "/mnt/cfs/algorithm/users/xianda.guo/code/GaitGraph/src/detector/detector_yolov3.py", line 33, in __init__
    self.model.load_darknet_weights(self.weights_path)
  File "/mnt/cfs/algorithm/users/xianda.guo/code/GaitGraph/src/detector/models.py", line 308, in load_darknet_weights
    conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
RuntimeError: shape '[128, 256, 1, 1]' is invalid for input of size 9038

**Comment by tteepe** [comment]
Hi,

I was able to reproduce your issue with freshly downloaded weights.
I added the same changes as: https://github.com/eriklindernoren/PyTorch-YOLOv3/commit/44a3e519c0e10bea371fc08b09be09bf26ab374e

Could you try re-downloading the weights with the new script?
